### ISSUE TITLE
Sublime Text 2 terminal.glue produces...

### ISSUE THREAD

**Issue by SFoskitt** [chrissimpkins/glue#37]
... this error for anything entered into the command prompt.

Traceback (most recent call last):
  File "./Glue.py", line 163, in muterun_runner
  File "./Glue.py", line 442, in muterun
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 0: ordinal not in range(128)

**Comment by chrissimpkins** [comment]
Thanks for the report!
